# Site settings
title: My corner of the internet.
email: dale.n.tibbetts@gmail.com
description: "Somewhere in space"
baseurl: ""
url: "http://motodale.io"

# Build settings
markdown: kramdown
permalink: pretty
