# Site settings
title: My corner of the internet.
email: generaljeefus@gmail.com
description: "Somewhere in space"
baseurl: ""
url: "http://motodale.github.io"
username: "motodale"

# Build settings
markdown: kramdown
permalink: pretty
